apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-orchestrator-sa
  namespace: aumovio-platform-deploy
  annotations:
    iam.gke.io/gcp-service-account: backend-orchestrator-sa@gcp1042-bv42.iam.gserviceaccount.com